// ESLint flat config for the mixpanel-headless-ts workspace (ESLint 10,
// `defineConfig` / `globalIgnores` from "eslint/config").
//
// Baseline: @eslint/js recommended + typescript-eslint recommended (R1.2:
// Prettier owns formatting; no iron-internal conventions adopted).
//
// R9.1 core-purity boundary: packages/core is isomorphic. It must not import
// Node built-ins (`node:*`, `fs`, `path`, `os`) or `undici`, and must not
// touch the `process` global. Enforced here and by the browser-bundle smoke
// test (scripts/browser-smoke.mjs) wired into `npm run check`.
import { defineConfig, globalIgnores } from "eslint/config";
import js from "@eslint/js";
import tseslint from "typescript-eslint";

const CORE_PURITY_MESSAGE =
  "packages/core is isomorphic (R9.1) and packages/browser is " +
  "browser-only (R9.3, b9-packets.md §0.4): no Node built-ins, no " +
  "undici. Node-specific code belongs in packages/node.";

export default defineConfig(
  globalIgnores([
    "**/node_modules/**",
    "**/dist/**",
    "**/coverage/**",
    // Local agent scratch (git-ignored per CLAUDE.md conventions) —
    // scratch .ts probe scripts are not repo code (QA 2026-08-17).
    ".notes/**",
    // Vendored verbatim from the analytics checkout — never repo-linted.
    "vendor/**",
    // Generated by scripts/generate-api-map.mjs — byte-stable, typechecked
    // but not linted (freshness test compares exact bytes).
    "conformance-runner/src/api-map.gen.ts",
    // Generated by scripts/generate-non-printable.py — CPython-pinned
    // printability table, typechecked but not linted.
    "packages/core/src/compat/non-printable.gen.ts",
  ]),
  js.configs.recommended,
  tseslint.configs.recommended,
  {
    // @eslint/js 10 promoted `no-useless-assignment` into `recommended`; it
    // flags six existing sites (report-links.ts, workspace.ts,
    // registration.ts, gen-error-codes.mjs). Held off here so the ESLint 10
    // move is a pure config port — Phase 4 (lint rules) enables it and fixes
    // the sites. The other two new recommended rules (`no-unassigned-vars`,
    // `preserve-caught-error`) are clean and stay on.
    rules: {
      "no-useless-assignment": "off",
    },
  },
  {
    // Repo maintenance scripts run under Node.
    files: ["scripts/**/*.mjs"],
    languageOptions: {
      globals: {
        console: "readonly",
        process: "readonly",
      },
    },
  },
  {
    // B9-R1 (b9-packets.md §0.4): packages/browser shares the core
    // purity boundary — browser globals only, no node:*; the browser
    // storage object is touched solely via an injected Storage-shaped
    // parameter in the localStorage adapter.
    files: ["packages/core/**/*.ts", "packages/browser/**/*.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            { name: "fs", message: CORE_PURITY_MESSAGE },
            { name: "path", message: CORE_PURITY_MESSAGE },
            { name: "os", message: CORE_PURITY_MESSAGE },
            { name: "undici", message: CORE_PURITY_MESSAGE },
          ],
          patterns: [
            {
              group: ["node:*"],
              message: CORE_PURITY_MESSAGE,
            },
          ],
        },
      ],
      "no-restricted-globals": [
        "error",
        {
          name: "process",
          message:
            "packages/core (R9.1) and packages/browser (R9.4: env is " +
            "node-only) must not read process; inject configuration instead.",
        },
      ],
    },
  },
);
