// "Copy as Markdown": the generated code and the result rows as a GFM
// table, ready to paste into an issue or a pull request. Numbers stay raw
// (the UI formats for display, the export must not lose precision); pipes
// and line breaks inside cells are escaped so the table cannot break.

/** What the export needs: the code that ran and the rows it produced. */
export interface MarkdownExport {
  /** The program text shown in the code panel. */
  readonly code: string;
  /** `rowColumns()` of the result. */
  readonly columns: readonly string[];
  /** `toRows()` of the result. */
  readonly rows: ReadonlyArray<Readonly<Record<string, unknown>>>;
}

/** The provenance line every export starts with. */
export const MARKDOWN_HEADER =
  "Generated by the mixpanel-headless-ts playground";

/**
 * Render one cell: raw numbers, escaped text, JSON for anything nested.
 *
 * @param value - The cell value.
 * @returns Cell text safe inside a GFM table row.
 */
function cell(value: unknown): string {
  if (value === null || value === undefined) {
    return "";
  }
  let text: string;
  if (typeof value === "string") {
    text = value;
  } else if (typeof value === "number" || typeof value === "boolean") {
    text = String(value);
  } else {
    text = JSON.stringify(value);
  }
  return text.replaceAll("|", String.raw`\|`).replaceAll(/\r?\n/gu, " ");
}

/**
 * Build the Markdown export.
 *
 * @param data - Code, columns and rows.
 * @returns The provenance line, the code in a `ts` fence, then the table.
 * @example
 * ```ts
 * toMarkdown({ code: "const result = await ws.query(\"Signup\");", columns: ["event", "count"], rows: [{ event: "Signup", count: 7 }] });
 * // "Generated by the mixpanel-headless-ts playground\n\n```ts\n…\n```\n\n| event | count |\n| --- | --- |\n| Signup | 7 |\n"
 * ```
 */
export function toMarkdown(data: MarkdownExport): string {
  const header = `| ${data.columns.map((column) => cell(column)).join(" | ")} |`;
  const divider = `| ${data.columns.map(() => "---").join(" | ")} |`;
  const body = data.rows.map(
    (row) =>
      `| ${data.columns.map((column) => cell(row[column])).join(" | ")} |`,
  );
  return [
    MARKDOWN_HEADER,
    "",
    "```ts",
    data.code.trimEnd(),
    "```",
    "",
    header,
    divider,
    ...body,
    "",
  ].join("\n");
}
