/**
 * OAuth redirect-return parsing: turn a pasted redirect URL or query
 * string into a `CallbackResult`, validating the CSRF `state`. Shared by
 * Node's callback server and paste completer and by the browser
 * `completeLogin` — the URL grammar is identical in both runtimes, so
 * the parser and its result type live here.
 *
 * @see mixpanel_headless._internal.auth.flow._parse_pasted_redirect
 * @see mixpanel_headless._internal.auth.callback_server.CallbackResult
 */

import { pythonStrip } from "../compat/python-strip.js";
import { OAuthError } from "../errors.js";
import { parseQs } from "./query-params.js";

/**
 * Result of a successful OAuth callback: the authorization code and the
 * echoed CSRF `state` (the frozen dataclass `CallbackResult`).
 *
 * @example
 * ```typescript
 * const result = new CallbackResult({ code: "ABC", state: "XYZ" });
 * // result.code === "ABC"; Object.isFrozen(result) === true
 * ```
 * @see mixpanel_headless._internal.auth.callback_server.CallbackResult
 */
export class CallbackResult {
  /** The authorization code from the OAuth provider. */
  readonly code: string;

  /** The state parameter for CSRF validation. */
  readonly state: string;

  /**
   * Construct a frozen result; strict-mode mutation throws `TypeError`,
   * the `FrozenInstanceError` twin.
   *
   * @param fields - The code/state pair.
   */
  constructor(fields: { readonly code: string; readonly state: string }) {
    this.code = fields.code;
    this.state = fields.state;
    Object.freeze(this);
  }
}

/**
 * Parse a pasted OAuth redirect URL or query string into a
 * {@link CallbackResult}, validating the CSRF `state`.
 *
 * @remarks
 * Accepts, whitespace-trimmed, a full redirect URL, a query string with
 * a leading `?`, or the bare `code=...&state=...` text. The `state`
 * check is what stops a hostile party from tricking the user into
 * pasting an attacker-supplied code. Exported because the Python suite
 * drives the "private" function directly.
 * @param line - The text the user pasted on stdin (Node) or the
 *   redirect-return URL the browser page received.
 * @param options - The `expectedState` generated by this login session.
 * @returns The extracted code/state pair.
 * @throws {@link OAuthError} - Empty paste (`OAUTH_PASTE_ERROR`), a
 *   provider `error=` param (`OAUTH_AUTH_DENIED`), missing `code` /
 *   `state` (`OAUTH_PASTE_ERROR`), or a state mismatch
 *   (`OAUTH_STATE_MISMATCH`).
 * @example
 * ```typescript
 * const result = parsePastedRedirect(
 *   "http://localhost:19284/callback?code=ABC&state=XYZ",
 *   { expectedState: "XYZ" },
 * );
 * // result.code === "ABC"
 * ```
 * @see mixpanel_headless._internal.auth.flow._parse_pasted_redirect
 */
export function parsePastedRedirect(
  line: string,
  options: { readonly expectedState: string },
): CallbackResult {
  const text = pythonStrip(line);
  if (text === "") {
    throw new OAuthError(
      "Empty paste — expected the redirect URL or `code=...&state=...`.",
      "OAUTH_PASTE_ERROR",
    );
  }
  // Strip everything up to and including the first `?` so both the
  // full URL form and the bare query-string form parse the same way.
  const questionMark = text.indexOf("?");
  const queryPart = questionMark === -1 ? text : text.slice(questionMark + 1);
  const params = parseQs(queryPart);
  const errorList = params.get("error");
  if (errorList !== undefined) {
    const err = errorList[0] as string;
    const desc = params.get("error_description")?.[0] ?? "";
    throw new OAuthError(
      `OAuth provider returned an error: ${err}${
        desc === "" ? "" : ` — ${desc}`
      }`,
      "OAUTH_AUTH_DENIED",
    );
  }
  const codeList = params.get("code") ?? [];
  const stateList = params.get("state") ?? [];
  if (codeList.length === 0 || stateList.length === 0) {
    throw new OAuthError(
      "Pasted text is missing `code` or `state` parameters. " +
        "Paste the full redirect URL (e.g., " +
        "http://localhost:.../callback?code=...&state=...).",
      "OAUTH_PASTE_ERROR",
    );
  }
  const code = codeList[0] as string;
  const state = stateList[0] as string;
  // Plain `!==` on purpose (not constant-time): one paste attempt per
  // login session (a mismatch fails the login), so there is no
  // repeated-guess timing oracle. Matches Python's `!=`.
  if (state !== options.expectedState) {
    throw new OAuthError(
      "State mismatch — the pasted text does not belong to this login session.",
      "OAUTH_STATE_MISMATCH",
    );
  }
  return new CallbackResult({ code, state });
}
