/**
 * OAuth redirect-return parsing — the core home of
 * `_parse_pasted_redirect` after the B9-R2
 * fetch-pure hoist (b9-packets.md §3.1 row 3; R10.8: shared internals
 * ported once, by name). Moved MECHANICALLY from
 * `packages/node/src/auth/flow.ts`; node re-exports from here and its
 * B8 suites stay green unchanged.
 *
 * HOIST NOTE (recorded in B9-R2-notes.md): `CallbackResult` — the
 * function's return type, a frozen two-field value class with zero
 * `node:*` surface — moves WITH it from
 * `packages/node/src/auth/callback-server.ts` (class body verbatim);
 * the node module re-exports it so every existing import path holds.
 * This is a mechanical necessity of the row, not a scope change.
 *
 * Consumers: node's callback server + paste completer (via re-export)
 * and the browser `completeLogin` (`redirect-flow.ts`) — the pasted /
 * redirect-returned URL grammar is identical in both runtimes.
 */

import { pythonStrip } from "../compat/python-strip.js";
import { OAuthError } from "../errors.js";
import { parseQs } from "./query-params.js";

/**
 * Result of a successful OAuth callback (port of the frozen dataclass
 * `CallbackResult`, `callback_server.py`).
 */
export class CallbackResult {
  /** The authorization code from the OAuth provider. */
  readonly code: string;

  /** The state parameter for CSRF validation. */
  readonly state: string;

  /**
   * Construct a result (frozen — strict-mode mutation throws
   * `TypeError`, the `FrozenInstanceError` twin).
   *
   * @param fields - The code/state pair.
   */
  constructor(fields: { readonly code: string; readonly state: string }) {
    this.code = fields.code;
    this.state = fields.state;
    Object.freeze(this);
  }
}

/**
 * Parse a pasted OAuth redirect URL or query string into a
 * {@link CallbackResult} (port of `_parse_pasted_redirect`,
 * `flow.py:51-115` — exported because the Python suite drives the
 * "private" function directly, `test_auth_flow.py:215`).
 *
 * Accepts (whitespace-trimmed): a full redirect URL, a query string
 * with leading `?`, or the bare `code=...&state=...` text. Validates
 * the pasted `state` against `expectedState` (CSRF — without this
 * check a hostile party could trick the user into pasting an
 * attacker-supplied code).
 *
 * @param line - The text the user pasted on stdin (node) or the
 *   redirect-return URL the browser page received.
 * @param options - The `state` generated by this login session.
 * @returns The extracted code/state pair.
 * @throws OAuthError - Empty paste (`OAUTH_PASTE_ERROR`), provider
 *   `error=` param (`OAUTH_AUTH_DENIED`), missing `code`/`state`
 *   (`OAUTH_PASTE_ERROR`), or state mismatch
 *   (`OAUTH_STATE_MISMATCH`).
 * @example
 * ```typescript
 * const result = parsePastedRedirect(
 *   "http://localhost:19284/callback?code=ABC&state=XYZ",
 *   { expectedState: "XYZ" },
 * );
 * // result.code === "ABC"
 * ```
 */
export function parsePastedRedirect(
  line: string,
  options: { readonly expectedState: string },
): CallbackResult {
  const text = pythonStrip(line);
  if (text === "") {
    throw new OAuthError(
      "Empty paste — expected the redirect URL or `code=...&state=...`.",
      "OAUTH_PASTE_ERROR",
    );
  }
  // Strip everything up to and including the first `?` so both the
  // full URL form and the bare query-string form parse the same way.
  const questionMark = text.indexOf("?");
  const queryPart = questionMark === -1 ? text : text.slice(questionMark + 1);
  const params = parseQs(queryPart);
  const errorList = params.get("error");
  if (errorList !== undefined) {
    const err = errorList[0] as string;
    const desc = params.get("error_description")?.[0] ?? "";
    throw new OAuthError(
      `OAuth provider returned an error: ${err}${
        desc === "" ? "" : ` — ${desc}`
      }`,
      "OAUTH_AUTH_DENIED",
    );
  }
  const codeList = params.get("code") ?? [];
  const stateList = params.get("state") ?? [];
  if (codeList.length === 0 || stateList.length === 0) {
    throw new OAuthError(
      "Pasted text is missing `code` or `state` parameters. " +
        "Paste the full redirect URL (e.g., " +
        "http://localhost:.../callback?code=...&state=...).",
      "OAUTH_PASTE_ERROR",
    );
  }
  const code = codeList[0] as string;
  const state = stateList[0] as string;
  // Plain `!==` on purpose (not constant-time): one paste attempt per
  // login session (a mismatch fails the login), so there is no
  // repeated-guess timing oracle. Matches Python's `!=`
  // (`flow.py` `_parse_pasted_redirect`). CLEANUP-PLAN 8.12.
  if (state !== options.expectedState) {
    throw new OAuthError(
      "State mismatch — the pasted text does not belong to this login session.",
      "OAUTH_STATE_MISMATCH",
    );
  }
  return new CallbackResult({ code, state });
}
