// Paths that are never linted or formatted: vendored, generated, or
// byte-frozen snapshots. The one list shared by `eslint.config.js`
// (`globalIgnores`) and `.prettierignore`; `tests/ignore-lists.test.ts` fails
// if the two drift apart. Everything here is either produced by a generator
// with a byte-exact freshness test (so reformatting would break that test)
// or mirrored verbatim from another repository.
//
// Patterns are gitignore-style, relative to the repo root; a trailing `/`
// means "directory and everything under it".

/**
 * @type {ReadonlyArray<{ readonly path: string; readonly why: string }>}
 */
export const FROZEN_PATHS = Object.freeze([
  {
    path: "vendor/",
    why: "Vendored verbatim from the analytics checkout (sha256 provenance).",
  },
  {
    path: "conformance-runner/corpus/",
    why: "Committed Python-corpus snapshot (scripts/sync-corpus.sh), verbatim bytes.",
  },
  {
    path: "docs/history/",
    why: "The port's process record (relocated from context/); frozen, not maintained.",
  },
  {
    path: "conformance-runner/src/api-map.gen.ts",
    why: "Generated by scripts/generate-api-map.mjs (byte-exact freshness test).",
  },
  {
    path: "conformance-runner/bridge-allowlist.gen.json",
    why: "Generated by scripts/generate-bridge-allowlist.mjs; header stamps input digests.",
  },
  {
    path: "packages/core/src/errors-codes.gen.ts",
    why: "Generated by scripts/generate-error-codes.mjs (byte-exact freshness test).",
  },
  {
    path: "packages/core/src/compat/non-printable.gen.ts",
    why: "Generated by scripts/generate-non-printable.py (CPython-pinned table).",
  },
  {
    path: "packages/core/src/compat/decimal-digits.gen.ts",
    why: "Generated CPython-pinned Unicode decimal-digit table.",
  },
  {
    path: "scripts/lib/python-reference-anchors.gen.json",
    why: "Generated by scripts/generate-python-reference-anchors.mjs; header stamps the corpus pin and generator sha256.",
  },
  {
    path: "packages/core/src/compat/whitespace.gen.ts",
    why: "Generated CPython-pinned Unicode whitespace table.",
  },
  {
    path: "docs/.vitepress/theme/demo/fixtures/demo-project.gen.ts",
    why: "Generated by scripts/generate-demo-fixtures.mjs (byte-exact freshness test).",
  },
]);

/**
 * Local-only trees that hold no repo code (git-ignored) and build output.
 *
 * @type {ReadonlyArray<{ readonly path: string; readonly why: string }>}
 */
export const LOCAL_PATHS = Object.freeze([
  { path: "node_modules/", why: "Dependencies." },
  { path: "dist/", why: "Build output (tsc -b, browser bundle)." },
  { path: "coverage/", why: "vitest coverage output." },
  {
    path: "docs/reference/",
    why: "TypeDoc output (npm run docs:api), regenerated per docs build; git-ignored.",
  },
  { path: "docs/.vitepress/dist/", why: "VitePress build output." },
  {
    path: "docs/.vitepress/cache/",
    why: "Vite dev/build cache for the docs site.",
  },
  { path: ".notes/", why: "Agent scratch notes (git-ignored)." },
  {
    path: ".claude/",
    why: "Claude Code agent worktrees (full repo copies, never repo code).",
  },
]);

/**
 * ESLint `globalIgnores` patterns: gitignore directories become `**\/dir/**`
 * so they match at any depth (node_modules, dist, coverage appear inside
 * workspaces too); root-anchored files stay as written.
 *
 * @returns {string[]} The ignore patterns, local trees first.
 */
export function eslintIgnorePatterns() {
  return [...LOCAL_PATHS, ...FROZEN_PATHS].map(({ path }) =>
    path.endsWith("/") ? `**/${path}**` : path,
  );
}
